# Generated by Django 4.2.6 on 2023-10-22 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_created_alter_listing_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Bidder',
            new_name='bidder',
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 22, 10, 50, 601385)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 22, 10, 50, 601385)),
        ),
    ]
