# Generated by Django 4.2.6 on 2023-10-23 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_bidder_bid_bidder_alter_bid_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 16, 45, 29, 324666)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 16, 45, 29, 324666)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
