# Generated by Django 4.2.6 on 2023-10-24 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bid_auction_alter_bid_amount_alter_bid_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 10, 22, 32, 621069)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 10, 22, 32, 621069)),
        ),
    ]
